### ISSUE TITLE
Accessability

### ISSUE THREAD

**Issue by Hugos68** [lichess-org/chessground#269]
Will there be support for keyboard only users to use tab and arrow keys to navigate the chessboard and also give every tile a seperate label that contains the piece that is standing on it? This would make it accessible to visually impaired people.

**Comment by benediktwerner** [comment]
On Lichess, users can enable keyboard input to make moves by typing them as chess notation instead, which generally seems like the better solution. And there's also a separate blind mode which optimizes the whole site for screen readers and doesn't use chessground at all.

Because of that, there currently aren't any plans to add accessibility features to chessground directly.

**Comment by Hugos68** [comment]
the way lichess does it sounds like the correct approach here!
