### ISSUE TITLE
Possible to drag and drop pieces off the board?

### ISSUE THREAD

**Issue by AhsanSarwar45** [lichess-org/chessground#291]
Hi, I was wondering if its possible to drag and drop pieces pieces off the board like in this chessboard.js [example](https://chessboardjs.com/examples#2006)?

**Comment by AhsanSarwar45** [comment]
An even better example would be the crazyhouse variant in lichess. Is that done using in built features, or custom-made?

**Comment by niklasf** [comment]
Dropping of the board is done via https://github.com/lichess-org/chessground/blob/f90358e77403673027ef3215cfe6266dc98bbc44/src/config.ts#L66

To drag a new piece onto the board, a little bit of glue is needed, because the pocket is not part of chessground. Call https://github.com/lichess-org/chessground/blob/f90358e77403673027ef3215cfe6266dc98bbc44/src/api.ts#L72 from the `mousedown` event handler of the pocket.

**Comment by AhsanSarwar45** [comment]
@niklasf Thank you, that worked. By any chance, is there a way to specify legal squares that the pieces can be dragged on to?

**Comment by niklasf** [comment]
For a *new* piece that's dragged in? Not directly, but you provide a callback
https://github.com/lichess-org/chessground/blob/f90358e77403673027ef3215cfe6266dc98bbc44/src/config.ts#L77
and reset the board state if needed. That's how lichess.org implements Crazyhouse drops.
